@startuml

start
:Execute user command;
:Parse user input;
:Determine command;
if() then ([list or find])

if () then ([list])
:Create new ListCommand;
:Update Model using Model.PREDICATE_SHOW_ALL_FOODS;
else ([find])
:Create new FindCommandParser;
:Generate predicate based on Prefix;
:Use predicate generated to create new FindCommand;
:Update Model using predicate in FindCommand;
endif

else([other commands])
:Perform relevant action;
endif

:Reflect changes in GUI to user;
stop

@enduml
