@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CalgoParser" as CalgoParser LOGIC_COLOR
participant ":HelpCommand" as HelpCommand LOGIC_COLOR
end box

[-> LogicManager : execute("help nom")
activate LogicManager

LogicManager -> CalgoParser : parseCommand("help nom")
activate CalgoParser

create HelpCommand
CalgoParser -> HelpCommand : new HelpCommand("nom")
activate HelpCommand

HelpCommand -> HelpCommand : addMessagesToMap()
activate HelpCommand
deactivate HelpCommand

HelpCommand -> HelpCommand : setKeySet()
activate HelpCommand
deactivate HelpCommand

HelpCommand --> CalgoParser : command
deactivate HelpCommand

CalgoParser --> LogicManager : command
deactivate CalgoParser

LogicManager -> HelpCommand : execute(model)
activate HelpCommand

HelpCommand -> HelpCommand : setFilteredGuide()
activate HelpCommand
deactivate HelpCommand

HelpCommand --> LogicManager : result
deactivate HelpCommand

'Hidden arrow to position the destroy marker below the end of the activation bar.
HelpCommand -[hidden]-> CalgoParser
destroy HelpCommand

[<--LogicManager : result

@enduml
