@startuml

start
if() then ([Calgo startup])
:Read from storage json file;

if () then ([storage file available])
:Obtain previously saved data;
else ([else])
:Obtain default entries;
endif
:Initialise UniqueFoodList using obtained information;

else([user update command])
:UpdateCommand for Food f;
:Add f to UniqueFoodList's internalList;

endif
:Sort UniqueFoodList's internalList;
:Reflect in GUI's Food Record;
stop

@enduml
