@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyFoodRecord <<Interface>>
Interface ReadOnlyConsumptionRecord <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Interface Comparable <<Interface>>
Class FoodRecord
Class ConsumptionRecord
Class ReadOnlyFoodRecord
Class ReadOnlyConsumptionRecord
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Food {
Class Carbohydrate
Class Calorie
Class DisplayFood
Class Food
Class Fat
Class Name
Class Protein
Class UniqueFoodList
}

Package Day {
Class DailyFoodLog
Class DailyGoal
Class UniqueDateToLogMap
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

FoodRecord .up.|> ReadOnlyFoodRecord
ConsumptionRecord .up.|> ReadOnlyConsumptionRecord

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" FoodRecord
ModelManager o--> "1" ConsumptionRecord
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs
Food .up.|> Comparable
DisplayFood .down.|> Food

FoodRecord *--> "1" UniqueFoodList
UniqueFoodList o--> "*" Food
Food *--> "1" Name
Food *--> "1" Calorie
Food *--> "1" Carbohydrate
Food *--> "1" Protein
Food *--> "1" Fat
Food *--> "*" Tag

ConsumptionRecord *--> "1" UniqueDateToLogMap
UniqueDateToLogMap o--> "*" DailyFoodLog
DailyFoodLog o--> "*" Food : contains >
ModelManager --> "0..1" DailyGoal

ModelManager -->"1" Food : has FilteredList of >
ModelManager -->"1" DisplayFood : has FilteredList of >
@enduml
