@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyFoodRecord <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class FoodRecord
Class ReadOnlyFoodRecord
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Food {
Class Carbohydrate
Class Calorie
Class ConsumedFood
Class Food
Class Fat
Class Name
Class Protein
Class UniqueFoodList
}

Package Day {
Class DailyFoodLog
Class DailyGoal
Class UniqueDateToLogMap
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

FoodRecord .up.|> ReadOnlyFoodRecord

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" FoodRecord
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs
ConsumedFood .down.|> Food

FoodRecord *--> "1" UniqueFoodList
UniqueFoodList o--> "*" Food
Food *--> "1" Name
Food *--> "1" Calorie
Food *--> "1" Carbohydrate
Food *--> "1" Protein
Food *--> "1" Fat
Food *--> "*" Tag

FoodRecord *--> "1" UniqueDateToLogMap
UniqueDateToLogMap o--> "*" DailyFoodLog
DailyFoodLog o--> "*" Food
ModelManager --> "0..1" DailyGoal

ModelManager -->"1" Food : filtered list
ModelManager -->"1" ConsumedFood : filtered list
@enduml
