@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package "Storage Component"{
Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface FoodRecordStorage <<Interface>>
Interface GoalStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonFoodRecordStorage
Class JsonGoalStorage
Class JsonSerializableGoal
Class JsonAdaptedGoal

Class ReportGenerator
Class ExportGenerator

StorageManager .up.|> Storage
StorageManager o--> UserPrefsStorage
StorageManager o--> FoodRecordStorage
StorageManager o--> GoalStorage

JsonGoalStorage .up.|> GoalStorage
JsonGoalStorage ..> JsonSerializableGoal
JsonSerializableGoal ..> JsonAdaptedGoal

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonFoodRecordStorage .up.|> FoodRecordStorage
JsonFoodRecordStorage .down.> JsonSerializableFoodRecord
JsonSerializableFoodRecord .down.> JsonAdaptedFood
JsonAdaptedFood .right.> JsonAdaptedTag
}
@enduml
