@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package "Storage Component"{
Interface Storage <<interface>>
Interface FoodRecordStorage <<interface>>
Interface ConsumptionRecordStorage <<interface>>
Interface UserPrefsStorage <<interface>>
Interface GoalStorage <<interface>>

Class "{abstract}\nDocumentGenerator"
Class ReportGenerator
Class ExportGenerator
Class StorageManager
Class JsonUserPrefsStorage
Class JsonFoodRecordStorage
Class JsonConsumptionRecordStorage
Class JsonGoalStorage
Class JsonSerializableGoal
Class JsonSerializableFoodRecord
Class JsonSerializableConsumptionRecord
Class JsonAdaptedFood
Class JsonAdaptedGoal
Class JsonAdaptedTag
Class JsonAdaptedDailyFoodLog

"{abstract}\nDocumentGenerator" <|-- ReportGenerator
"{abstract}\nDocumentGenerator" <|-- ExportGenerator

StorageManager .up.|> Storage
StorageManager o--> "1" UserPrefsStorage
StorageManager o--> "1" ConsumptionRecordStorage
StorageManager o--> "1" FoodRecordStorage
StorageManager o--> "1" GoalStorage

JsonConsumptionRecordStorage .up.|> ConsumptionRecordStorage
JsonConsumptionRecordStorage .down.> JsonSerializableConsumptionRecord
JsonSerializableConsumptionRecord .down.> JsonAdaptedDailyFoodLog
JsonAdaptedDailyFoodLog .down.> JsonAdaptedFood

JsonGoalStorage .up.|> GoalStorage
JsonGoalStorage ..> JsonSerializableGoal
JsonSerializableGoal ..> JsonAdaptedGoal

JsonUserPrefsStorage .up.|> UserPrefsStorage

JsonFoodRecordStorage .up.|> FoodRecordStorage
JsonFoodRecordStorage .down.> JsonSerializableFoodRecord
JsonSerializableFoodRecord .down.> JsonAdaptedFood
JsonAdaptedFood .left.> JsonAdaptedTag
}
@enduml
