@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class GoalDisplay
Class FoodListPanel
Class FoodCard
Class DailyListPanel
Class ConsumedFoodCard
Class StatusBarFooter
Class CommandBox
Class GraphPanel
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow *-down-> HelpWindow
MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> GoalDisplay
MainWindow *-down-> FoodListPanel
MainWindow *-down-> DailyListPanel
MainWindow *-down-> StatusBarFooter
MainWindow *-down-> GraphPanel

FoodListPanel -down-> FoodCard
DailyListPanel -down-> ConsumedFoodCard

MainWindow -left-|> UiPart


ResultDisplay --|> UiPart
GoalDisplay --|> UiPart
CommandBox --|> UiPart
FoodListPanel --|> UiPart
FoodCard --|> UiPart
DailyListPanel --|> UiPart
ConsumedFoodCard ---|> UiPart
StatusBarFooter --|> UiPart
HelpWindow -down-|> UiPart
GraphPanel --|> UiPart


GraphPanel ..> Model
FoodCard ..> Model
ConsumedFoodCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

DailyListPanel -[hidden]left- FoodListPanel
FoodListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
